# Generated by Django 4.0.4 on 2022-06-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=225)),
                ('discount_price', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
